apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-manager-rolebinding-frpdf
  namespace: uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-manager-role-frpdf
subjects:
- kind: ServiceAccount
  name: deployment-cron-uat
  namespace: uat
