apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-manager-role-frpdf
  namespace: prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/exec"]
  verbs: ["create", "get"]
