---
apiVersion: v1
kind: Service
metadata:
  name: eycomplyapp-{{PORTAL}}-service-{{MICROSVC}}
spec:
  type: ClusterIP
  selector:
    app: {{PORTAL}}-deploy-{{MICROSVC}}
  ports:
  - name: {{MICROSVC}}-port
    port: {{DOCKER_PORT}}
    targetPort: {{DOCKER_PORT}}
    protocol: TCP
