---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eycomplyapp-{{PORTAL}}-ingress-object-{{MICROSVC}}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      limit_req_status 429;
      more_clear_headers "Server";
    nginx.ingress.kubernetes.io/custom-http-errors: "403,502"
    nginx.ingress.kubernetes.io/enable-modsecurity: "false"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{PROXY_TIMEOUT}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{PROXY_TIMEOUT}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{PROXY_TIMEOUT}}"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "{{PROXY_TIMEOUT}}"
    nginx.ingress.kubernetes.io/proxy-body-size: {{PROXY_BODY_SIZE}}
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: {{PROXY_BODY_SIZE}}
    nginx.ingress.kubernetes.io/rewrite-target: {{INGRESS_REWRITE}}/$6
    nginx.ingress.kubernetes.io/limit-rpm: "{{LIMIT_RPM}}"
    nginx.ingress.kubernetes.io/limit-rps: "{{LIMIT_RPS}}"
    nginx.ingress.kubernetes.io/limit-connections: "{{LIMIT_CONNECTIONS}}"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRequestBodyLimit 1073741824
spec:
  ingressClassName: nginx
  rules:
  - host: {{AKS_LB}}-ingress-lb.eastus.cloudapp.azure.com
    http:
      paths:
      - path: {{INGRESS_PATH}}
        pathType: ImplementationSpecific
        backend:
          service:
            name: eycomplyapp-{{PORTAL}}-service-{{MICROSVC}}
            port:
              number: {{DOCKER_PORT}}
