variables:
  tenant-ingress-pattern: "is|admin|gs|trp|pimco2|ag2"
  
  audit-ingress-rewrite: audit
  authentication-ingress-rewrite: /authenticationService
  authorization-ingress-rewrite: /authorizationService
  bcmregreporting-ingress-rewrite: /bcmdemo
  bcmregmonitoring-ingress-rewrite: /bcmregmonitoringservice
  boardreporting-ingress-rewrite: /boardreporting
  camundawrapper-ingress-rewrite: cws
  clamav-ingress-rewrite: /clamav
  comments-ingress-rewrite: /commentaryService
  configuration-ingress-rewrite: /configurationService
  configserver-ingress-rewrite: /config-server
  dataprovider-ingress-rewrite: /dataProviderService
  discovery-ingress-rewrite: /eurekaService
  dlqprocessor-ingress-rewrite: dlqProcessorService
  dlqprocessorui-ingress-rewrite: ""
  dmsdataintake-ingress-rewrite: /dmsdataintakeservice
  document-ingress-rewrite: /documentService
  download-ingress-rewrite: /downloadService
  expensereporting-ingress-rewrite: /expReportingService
  finreport-ingress-rewrite: /finreportservice
  gateway-ingress-rewrite: ""
  logging-ingress-rewrite: /logging
  metadata-ingress-rewrite: /metadataService
  notificationclient-ingress-rewrite: /notificationClientService
  notificationengine-ingress-rewrite: /notificationEngineService
  notifieragent-ingress-rewrite: /notifierAgentService
  outboundgateway-ingress-rewrite: /outboundgatewayService
  frpdfextraction-ingress-rewrite: /frpdfextractionService
  pbireport-ingress-rewrite: /pbireportService
  regreporting-ingress-rewrite: /regReportingCoreService
  rrcollaboration-ingress-rewrite: /rrCollaborationService
  sbadmin-ingress-rewrite: sbAdminService
  sendoutengine-ingress-rewrite: /sendoutEngineService
  standardizergateway-ingress-rewrite: /standardizergatewayService
  taxreporting-ingress-rewrite: /taxReportingCoreService
  tracker-ingress-rewrite: tracker
  topsides-ingress-rewrite: /topsidesService
  trackerui-ingress-rewrite: ""
  zipkin-ingress-rewrite: /srvzipkin
  zipkinui-ingress-rewrite: /zipkin
  fry9c-ingress-rewrite: /bcmfry9cService
  fry9cdataload-ingress-rewrite: /fry9cdataloadSerive
