version: '3'
services:
    eycomply-app:
      image: eycomplynonprod.azurecr.io/eyc2/microservices/${MICROSVC}:${TAG}
      build:
        dockerfile: Dockerfile
        context: .
      ports:
        - "4080:8080"
